# Generated by Django 5.0.7 on 2024-07-17 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_liketext_delete_dars_baho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darslar',
            old_name='name',
            new_name='dars',
        ),
        migrations.RenameField(
            model_name='darslar',
            old_name='izoh',
            new_name='izohi',
        ),
        migrations.RenameField(
            model_name='darslar',
            old_name='kurs',
            new_name='kursi',
        ),
        migrations.RenameField(
            model_name='darslar',
            old_name='muallif',
            new_name='muallifi',
        ),
        migrations.RenameField(
            model_name='darslar',
            old_name='dars_videosi',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='kurslar',
            old_name='kurs',
            new_name='kursi',
        ),
        migrations.RenameField(
            model_name='kurslar',
            old_name='muallif',
            new_name='muallifi',
        ),
        migrations.AlterUniqueTogether(
            name='darslar',
            unique_together={('dars',)},
        ),
        migrations.AlterUniqueTogether(
            name='kurslar',
            unique_together={('kursi',)},
        ),
        migrations.CreateModel(
            name='Izohlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izohi', models.TextField()),
                ('darsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.darslar')),
                ('muallifi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Izoh',
        ),
    ]
